var TREE_ITEMS = [
	[' ระบบงาน', null,
		[' Time Attendance', 0,
				[' บันทึกรายการประจำวัน', 0,
						[' Time Attendance', 'security.htm?reqCode=CTPNMT001'],
				],
				[' สอบถาม', 0,
						[' View Time Attendance', 'security.htm?reqCode=CTPNQY001'],
				],
				[' รายงาน', 0,
						[' Report Time Attendance ', 'security.htm?reqCode=CTPNRP001'],
				],
		],
		[' Personal Evaluation', 0,
				[' บันทึกรายการประจำวัน', 0,
						[' Personal Evaluation', 'security.htm?reqCode=CTPNMT002'],
				],
				[' สอบถาม', 0,
						[' View Personal Evaluation', 'security.htm?reqCode=CTPNQY002'],
				],
				[' รายงาน', 0,
						[' Report Personal Evaluation', 'security.htm?reqCode=CTPNRP002'],
				],
		],
		[' เงินเดือน', 0,
				[' บันทึกรายการประจำวัน', 0,
						[' CTRWMT003', 'security.htm?reqCode=CTRWMT003'], 
						[' CTRWMT004', 'security.htm?reqCode=CTRWMT004'], 
				],
				[' สอบถาม', 0,
						[' สอบถาม1', 0],
						[' สอบถาม2', 0],
				],
				[' รายงาน', 0,
						[' รายงาน1', 0],
						[' รายงาน2', 0],
				],
		 ],
	]
];
